version: 2
updates:
  - package-ecosystem: npm
    directory: /
    dependency-type: production
    schedule:
      interval: monthly
    cooldown:
      default-days: 3
    open-pull-requests-limit: 25

  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 3
    open-pull-requests-limit: 25
